name: event2go
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  english_words: ^3.1.0
  contacts_service: ^0.0.6
  google_sign_in: ^3.0.4
  firebase_auth: ^0.5.14
  flutter_masked_text: ^0.5.0
  # date formatter, https://pub.dartlang.org/packages/intl#-readme-tab-
  intl: ^0.15.7
#  firebase_auth:
#    git:
#      url: git@github.com:flutter/plugins.git
#      path: packages/firebase_auth
#      ref: 000cd4c7f8b9eba0feef714a08ff8a13f0f81990
#      ref: 075897e

dev_dependencies:
  flutter_test:
    sdk: flutter


# [+] Help
# ios 'Flutter/Flutter.h' not found
# https://github.com/dart-flitter/flutter_webview_plugin/issues/78

# open ios project, run from terminal
# open ios/Runner.xcworkspace

# permission denied
# chmod a+x /Users/Username/Project/.../ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh
# [-] Help end

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
