name: event2go
description: A new Flutter application.


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'
#  sdk: ">=2.3.0-dev.0.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  english_words: ^3.1.0
  contacts_service: ^0.6.3
  google_sign_in: ^5.2.1
#  firebase_core: ^0.7.0
#  firebase_auth: ^0.20.1
  # date formatter, https://pub.dartlang.org/packages/intl#-readme-tab-
  intl: ^0.17.0
  # used for @immutable
#  firebase_auth: ^0.5.14
#  intl: ^0.15.7
  flutter_masked_text: ^0.6.0
#  permission_handler: ^8.2.5
  meta: ^1.1.6
  http: ^0.13.4
#  todo remove from app, move to module
#  flutterfire_ui: ^0.4.0+4
#  firebase_auth: ^3.3.16
#  firebase_core: ^1.15.0

  # https://flutter.dev/docs/development/data-and-backend/json#code-generation
  # $> flutter packages pub run build_runner build
  json_annotation: ^3.0.1
  # https://github.com/flutterchina/dio#examples
  dio: ^4.0.6
  content_feed:
    path: features/content_feed
  networking:
    path: features/networking
  home:
    path: features/home
  auth:
    path: features/auth

https://flutter:
  dev/docs/development/data-and-backend/json#code-generation:
#  firebase_auth:
#    git:
#      url: git@github.com:flutter/plugins.git
#      path: packages/firebase_auth
#      ref: 000cd4c7f8b9eba0feef714a08ff8a13f0f81990
#      ref: 075897e

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.5

#environment:
#    sdk: '>=1.23.0 <3.0.0'

# [+] Help
# ios 'Flutter/Flutter.h' not found
# https://github.com/dart-flitter/flutter_webview_plugin/issues/78

# open ios project, run from terminal
# open ios/Runner.xcworkspace

# permission denied
# chmod a+x /Users/Username/Project/.../ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh
# [-] Help end

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
